# Generated by Django 5.1 on 2024-09-05 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_publication',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
