# Generated by Django 5.1 on 2024-09-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_date_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_publication',
        ),
    ]
